- fix_yahoo_finance/__init__.py
Separating data frames on multiple requests by the user.
fixes #27
> Solved issue of merging dataframes.

- yfinance/__init__.py
Sometimes the priceHint suggested by Yahoo is not accurate. Compare, for example, the prices retrieved for this fund:
https://uk.finance.yahoo.com/quote/0P00006C6F.L/history?p=0P00006C6F.L
with prices available from other sources, for example Financial Times:
https://markets.ft.com/data/funds/tearsheet/historical?s=GB00B0WDH832:GBX
The underlying data returned by Yahoo has enough precision, so rounding causes a loss of accuracy.
The change is backward compatible: unless the newly introduced parameter is specified, the behaviour remains the same.
> Ability to avoid rounding the values retrieved from Yahoo

- yfinance/__init__.py
I put 'rename=True' for the namedtuple that symbol requires to put a dot. eg '1155.KL' or 'PTT.BK' or 'MU7.SI'
> Update from my issue #88

- README.rst
> fix typo (~msgt~ -> msft)

- requirements.txt
- setup.py
When running through the example code, got the following message:
`ImportError: lxml not found, please install it`
So, figured I'd fix up the dependencies while at it.
> add a missing dependency

- yfinance/utils.py
> Fix deprecation warnings due to invalid escape sequences.

- yfinance/ticker.py
Removes dividends property (included twice originally)
> CLN: Remove duplicate property

- README.rst
> Typo fix in README

- CHANGELOG.rst
- README.rst
- meta.yaml
- runtest.py
- setup.py
- yfinance/base.py
- yfinance/ticker.py
This combines changes proposed across PRs #456, #430, #406, #397, #375, #371, #365, #337, #316, #305, #220, #215, #203, #196, #187, #168, #442, #428, #409, #388, #345, #339, #299.  
Also added unit tests which use tickers that were identified as causing some of the reported errors.  
Updated change log.
updated setup.
> Fix for institutional investors issue and added mutual fund holders to ticker

- yfinance/base.py
Ïncluded financialData  in order to be able to dowload among other ROA and ROE
> Add financialData to info

- yfinance/base.py
Fix was found [here](https://stackoverflow.com/a/65260400).
| Old Date | New Date |
| ---------- | ----------- |
|![1hr old](https://user-images.githubusercontent.com/7155643/111642704-b2f2b880-87d4-11eb-83fb-15f461c90118.png) | ![1hr new](https://user-images.githubusercontent.com/7155643/111642731-b7b76c80-87d4-11eb-81ec-4149344bfc3a.png)|
> Fix for issue of 1 hour interval incorrect date

- README.rst
I've added this update as per https://twitter.com/Aroussi/status/1291009917818736641 with Ran Aroussi. This update adds a link to a stack overflow answer, which discusses dealing with multi-level column names.
> Add link to SO question on how to deal with multi-level dataframe column name

- yfinance/base.py
Reason is that a failure would be harmful without a graceful try+except
> try + except still required - topHoldings, summaryDetail

- yfinance/base.py
- yfinance/multi.py
- yfinance/tickers.py
> Adding possibilty to modify timeout parameter of requests.get function.

- yfinance/ticker.py
passing utc true as default and adding dt field as series
fix #889
> Bug Fix: Timezone value passed on to the option_chain throws TypeError

- README.md
- meta.yaml
- requirements.txt
- setup.py
Recent PR that fixes timezone stuff https://github.com/ranaroussi/yfinance/pull/1048 uses 'appdirs' module to cache tz data. But I forgot to add to requirements before merging.
> Add new dep 'appdirs' for recent tz-fixes PR

- yfinance/multi.py
> Fix download(ignore_tz=True) for single ticker

- yfinance/base.py
Add error check for 'period' ; simplify err-msg handling ; new arg 'raise_errors' to control print-vs-Exception
> Improve error message handling

- tests/prices.py
- yfinance/base.py
This time I actually verify repaired-weekly data against daily data (in a unit test). There were some differences, now addressed.
> Fix price repair ; Improve repair test

- yfinance/base.py
Duplicating PR #1064 for version 0.1.*
> Bugfix: Get logo url when no website exists

- tests/prices.py
- tests/ticker.py
- yfinance/base.py
- yfinance/multi.py
- yfinance/tickers.py
- yfinance/utils.py
Fixed formatting warning reported by the code inspection in PyCharm.
This will make it easier to spot the real errors when you use a code inspector tool.
Project should probably use some sort of automatic code formatter and checker in the future but this is a little step in adhering to PEP8.
> Fixed some of the formatting warnings reported by PyCharm IDE

- tests/prices.py
- tests/ticker.py
- yfinance/base.py
- yfinance/multi.py
- yfinance/tickers.py
- yfinance/utils.py
Reverts ranaroussi/yfinance#1122
> Revert "Fixed some of the formatting warnings reported by PyCharm IDE"

- README.md
Hi there,
Love the project. The dot notation on the readme file doesn't seem to work, I get an attribute error.
It's a small fix and I hope it might help somebody.
Thanks for considering this change.
> Update README.md with new notation

- yfinance/base.py
- yfinance/utils.py
Check if bad timezone value in cache or returned by Yahoo. Bad = ticker not listed.
Fix #1137
> Backport ticker tz verification for nice error

- test_yfinance.py
- yfinance/base.py
Backporting changes from #1138
> Move get 'trailingPegRatio' into _get_info(), simplify & optimise

- tests/prices.py
- tests/ticker.py
- yfinance/base.py
- yfinance/multi.py
- yfinance/tickers.py
- yfinance/utils.py
This is same at previous PR just with fixed merge conflicts
> Fixed some of the formatting errors reported by PyCharm as well as simplified some code constructs.

- test_yfinance.py
- tests/ticker.py
- yfinance/base.py
Improve handling of bad ticker, and add a good test
Add session to tests/ticker.py
Remove redundant `get_earnings_history()`
> Improve bad ticker handling

- tests/prices.py
- yfinance/base.py
Add `_fix_zero_prices()`, which fixes price=0 errors
Fix 100x outlier detection logic:
- switch `median_filter` boundary mode from 'mirror' -> 'wrap', to avoid duplicating outliers
- loosen the tolerance
Refactor:
- move reconstruction logic into `Ticker._reconstruct_interval()`
- refactor repair tests to use hardcoded (but real) data
> Repair: add zero-price repair + refactor

- yfinance/base.py
Dividend was being merged with the previous day, not the same day. This is because Yahoo returns todays price data with time  =now(), but dividend time = market open (so before). This fixes merge by pulling up datetime->date conversion.
> Fix merging events with day/wk/mth prices

- requirements.txt
- tests/prices.py
- tests/ticker.py
- yfinance/base.py
- yfinance/data.py
- yfinance/exceptions.py
- yfinance/scrapers/analysis.py
- yfinance/scrapers/fundamentals.py
- yfinance/scrapers/holders.py
- yfinance/scrapers/quote.py
- yfinance/ticker.py
- yfinance/utils.py
Made fundamentals, quote, analysis and holders into lazy scraped modules in order to improve performance and code maintainability.
> Major refactoring

- yfinance/base.py
- yfinance/utils.py
> Fix localizing midnight when non-existent (DST) #1174

- tests/ticker.py
- yfinance/base.py
- yfinance/scrapers/fundamentals.py
- yfinance/utils.py
Add whitespace to financials tables keys, e.g. "FreeCashFlow" -> "Free Cash Flow" #1186
Also restored @git-shogg code for creating nested index but disabled, eventually will be good to complete.
> Fix financials formatting

- yfinance/base.py
Fix performance degradation from #1166 by replacing `info[]` access with metadata access. Requires small change to capital gains logic - always request it, but only return for ETFs & mutual funds.
@thirumalairajr Any obvious problems?
> Get quote type from metadata instead info[] -> faster

- tests/ticker.py
Make sure calling ticker history does not introduce any requests to yahoo that could trigger spam-block long before the chart API.
> Test to verify ticker history request.

- yfinance/base.py
- yfinance/utils.py
- Tolerate merging daily dividend event without matching prices interval (just append)
- Move price-repair to after merge, to fix these missing prices intervals
- Improve bad-price detection & repair
> Improve handling dividends without matching price interval

- tests/prices.py
- yfinance/base.py
- yfinance/utils.py
Minimise _reconstruct_intervals() #requests ; Refine when to repair NaNs
> Improve price repair

- README.md
- meta.yaml
- requirements.txt
- setup.py
Raise `lxml` minimum version #1222
Raise `pandas` minimum version #1230
Synchronise requirement versions across all files
> Raise reqs min versions (lxml, pandas)

- yfinance/base.py
This repair function was being blocked by zeroes in price data (divide-by-zero error).
> Fix '100x price' repair

- yfinance/base.py
- yfinance/data.py
- yfinance/exceptions.py
- yfinance/scrapers/fundamentals.py
Nicely intercept parse errors in `get_json_data_stores` & `_create_financials_table_old`
Improve exception messages
Fix typo 'YFiance'
> Improve financials error handling

- test_yfinance.py
- yfinance/utils.py
> Fix quotes html parsing when missing root.App.main

- tests/ticker.py
- yfinance/base.py
- yfinance/scrapers/quote.py
- Fix symbols without trading history or share count
- Improve migration message
- Add "regular_market_previous_close" because different to "previous_close"
- Add `get(key, default=None`
- Make JSON-serializable via `toJSON()`
Issues fixed: #1357 #1360
> Ticker.fast_info: fix teething bugs

- README.md
Add to top of README:
- summary of why `yfinance` breaking recently
- what the heck is `fast_info`?
> README: comment on instability, tidy Ticker 'Quick start'

- yfinance/scrapers/quote.py
Addresses recent issue where calling Ticker.info would occasionally result in a TypeError Exception at line 287.
> Catch TypeError Exception

- yfinance/data.py
@Meborl discovered how to use the ~10000 new key-value pairs to decrypt - join the last 4. [Link](https://github.com/ranaroussi/yfinance/issues/1338#issuecomment-1406945967)
> Add another backup decrypt option

- yfinance/base.py
- yfinance/utils.py
Most of optimisation is in price repair feature.
Also optimised formatting of `history_metadata["tradingPeriods"]` table
> Optimise recent new features in `history`

- yfinance/base.py
Fix `fast_info[]` dying if history metadata incomplete/missing
Fix price repair dying when no finer-grained data available
And sneaking in another fix unrelated to title:
Fix `_fix_unit_mixups()` report
> Improve handling missing price history

- yfinance/base.py
- yfinance/multi.py
> Clarify that interval is [start; end) in docstrings

- tests/prices.py
- yfinance/utils.py
Addressing issue #1453 
Simple fix and test added.
Thanks to @ValueRaider for the suggestions.
> Adding fix and test for aggregating Capital Gains

- tests/prices.py
- yfinance/base.py
> Fix filtering events older than prices for merging

- yfinance/base.py
- yfinance/utils.py
- move drop-duplicates to before repair
- fix `format_history_metadata()` processing "regular" column, and order columns sensibly
- fix Pandas & Numpy warnings
> Various fixes to price data processing

- tests/prices.py
- yfinance/base.py
Price repair changes:
- if user requests price repair, add 'Repaired?' bool column showing what rows were repaired.
- fix price repair requesting <1d data beyond Yahoo's limit.
- fix logger messages
> Price repair: add 'Repaired?' column, and a bugfix

- tests/ticker.py
- yfinance/scrapers/quote.py
> Fix '_np not found', tweak 'info[] fixed' message

- yfinance/base.py
Fix merging prices & events if prices empty.
If user requested price repair, ensure 'Repaired?' column always present.
> Price fixes

- tests/prices.py
- yfinance/utils.py
An out-of-range dividend was breaking merge with 1mo-prices (#1550), so fixed that. Also replaced the mega-loop with Numpy, much clearer now. Improved its tests.
> Fix prices-events merge

- yfinance/utils.py
When a dividend or stock split event is scheduled for the next trading session, in future before market open, then Yahoo returns this without corresponding price data. So yfinance merge was discarding future events.
Now, append a NaN row to prices to contain future event.
> Fix merge future div/split into prices

- README.md
More emphasis that user should review the Wiki for the full API for `download()` and `Ticker.history()`
> Emphasise API on Wiki

- yfinance/scrapers/quote.py
It fixes the error: unauthorized, invalid crumb
> Fix "unauthorized, invalid crumb"

- tests/ticker.py
- yfinance/scrapers/quote.py
> Fix info[] missing values

- .github/ISSUE_TEMPLATE/bug_report.yaml
Turns out a new issue displays exactly same as in preview.
> Fix yaml issue rendering

- yfinance/base.py
- yfinance/const.py
- yfinance/utils.py
Commit a4d7d6c5774e1d572c9254429275a6c41ed942a1 introduced a circular import into utils.py. Fixes #1642
> Fix circular import in utils.py

- yfinance/utils.py
Satisfy unit test `test_intraDayWithEvents_tase` https://github.com/ranaroussi/yfinance/blob/5b1605b5a194d4df3cec81056bee6ed61294bb7d/tests/prices.py#L180C9-L180C37
> Fix merging pre-market events with intraday prices

- tests/ticker.py
- yfinance/base.py
> Fix _get_ticker_tz() args, were being swapped. Improve its unit test

- yfinance/scrapers/history.py
Sort direction of prices was being flipped **during** price repair, allowing for data corruption when restoring original data where repair failed.
> Price repair bug-fix

- yfinance/scrapers/history.py
@cottrell FYI, had to adjust your fix in #1865
> Fix potential for price repair to discard price=0 rows

- yfinance/scrapers/history.py
Price repair logic treats price changes with volume=0 as bad. But with FX, volume always 0, so don't attempt repair (unless other problems).
> Don't price-repair FX volume=0, is normal

- tests/test_ticker.py
- yfinance/scrapers/quote.py
This PR does the following: 
- implements the fetching of the sustainability data 
- Enables tests related to sustainability fetching
> Sustainability Fetching Implementation

- .gitignore
- yfinance/scrapers/history.py
#1916 Fixed limited period auto adjust with "max" period value
accidentally misspelled 'period' for branch name...
> fixed history fetching when period='max'

- yfinance/scrapers/history.py
If 1d/1wk close changes without volume, tag as bad for repair.
> Price repair zeroes: improve for 1d+ data

- yfinance/utils.py
- %% -> %
- Fixes: https://github.com/ranaroussi/yfinance/issues/2019
sample check
```python
yf.download('GE')
```
prints:
```
[*********************100%***********************]  1 of 1 completed
```
> Fix minor typo

- yfinance/scrapers/history.py
Revert #2027, breaks with prepost=True
> Revert PR #2027, breaks with prepost=True

- README.md
This PR fixes the typo in the README.md file outlined in issue #2038
> Fix typo in README.md #2038

- yfinance/scrapers/history.py
Confirmed fixes #2046 (@tapadeep FYI)
> Fix IndexError in some history() debug messages

- yfinance/multi.py
> Fix typo in multi.py download() docs

- yfinance/utils.py
> Fix prices-clean discarding both duplicate last rows instead of 1/2

- README.md
- doc/source/reference/examples/search.py
- doc/source/reference/index.rst
- doc/source/reference/yfinance.search.rst
- tests/test_search.py
- yfinance/__init__.py
- yfinance/base.py
- yfinance/search.py
- yfinance/utils.py
This PR introduces a new search feature to the `yfinance` library that connects the functionality to search for tickers via the Yahoo Finance API.
I am open to further discussion and will be happy to complete the feature if the maintainers agree that this is a right addition to the package.
> Feature: Add search feature

- yfinance/scrapers/holders.py
> Fix: Failed to parse holders JSON data 

- yfinance/scrapers/quote.py
- Extended Yahoo Finance quote fetcher to include pre-market and post-market prices
- Improved dictionary processing to handle nested data structures more consistently
- Fixed maxAge normalization to handle non-dictionary values
- Added support for market state tracking
The stock data fetcher now includes additional market data:
- Pre-market price
- Post-market price
- Market state (pre/regular/post)
These values are now available in the ticker.info dictionary alongside regular market data.
This should fix https://github.com/ranaroussi/yfinance/issues/1393
> Add pre- / post-stock prices (and other useful information)

- yfinance/scrapers/holders.py
Extra back slash. Request was being sent to wrong endpoint
Closes https://github.com/ranaroussi/yfinance/issues/2242
> Fix: Bad data in Holders

- yfinance/const.py
- yfinance/data.py
Targeting main branch because of urgent bug fix
Closes #2276
> Fix: Change user-agent headers to resolve yfinance download issues

- yfinance/scrapers/history.py
Fix #2349. Problem was localizing timestamp to not UTC. Might have been dropping dividends/splits/capital-gains in Asian markets (UTC+N) if they occurred near end of trading day.
> Fix converting end epoch to localized dt

- yfinance/base.py
- yfinance/domain/domain.py
- yfinance/domain/industry.py
- yfinance/domain/market.py
- yfinance/domain/sector.py
- yfinance/lookup.py
- yfinance/multi.py
- yfinance/scrapers/analysis.py
- yfinance/scrapers/fundamentals.py
- yfinance/scrapers/funds.py
- yfinance/scrapers/history.py
- yfinance/scrapers/holders.py
- yfinance/scrapers/quote.py
- yfinance/screener/screener.py
- yfinance/search.py
- yfinance/tickers.py
- yfinance/utils.py
Fix #2417
Also sneak in fix for #2413
> Fix 'proxy deprecation' msg

- yfinance/screener/screener.py
This is to `main` branch as it is a major bug fix.
Yahoo changed from `size` to `count` param and are now using the `Query1` url. This pr reflects those changes
Closes:
#2419 
and maybe some more.
@ValueRaider
> Fix Screener

- yfinance/data.py
- yfinance/domain/domain.py
- yfinance/scrapers/analysis.py
- yfinance/scrapers/funds.py
- yfinance/scrapers/holders.py
- yfinance/scrapers/quote.py
- yfinance/screener/screener.py
- yfinance/utils.py
Fix the rate-limit errors starting today
> Disable setting user-agent, curl_cffi does that

- yfinance/data.py
The curl_cffi change broke cookie caching & reuse.
Fixes #2456
> Fix cookie reuse/caching + logging

- yfinance/screener/screener.py
> Fix screen + offset

- doc/source/advanced/caching.rst
- yfinance/data.py
- yfinance/pricing_pb2.py
> Deprecate using requests_cache etc, only curl_cffi works

- yfinance/live.py
> Fix type hints in live.py

- yfinance/live.py
> Fix ALL type hints in live.py

- yfinance/base.py
- yfinance/cache.py
Cache ISIN -> ticker symbol, avoid repeating lookup.
> Feature: ISIN cache

- yfinance/base.py
- yfinance/domain/domain.py
- yfinance/domain/industry.py
- yfinance/domain/market.py
- yfinance/domain/sector.py
- yfinance/lookup.py
- yfinance/multi.py
- yfinance/scrapers/analysis.py
- yfinance/scrapers/fundamentals.py
- yfinance/scrapers/funds.py
- yfinance/scrapers/history.py
- yfinance/scrapers/holders.py
- yfinance/scrapers/quote.py
- yfinance/screener/screener.py
- yfinance/search.py
- yfinance/ticker.py
- yfinance/tickers.py
- yfinance/utils.py
Also remove 'basic_info', been deprecated a long time.
> Replace 'print_once' with warnings.

- yfinance/multi.py
> Fix download()+ISIN

- yfinance/exceptions.py
- yfinance/scrapers/history.py
> Prices: fix 'period' arg when start or end set

- yfinance/scrapers/history.py
> Prices: fix behaviour change on end=None
