ranaroussi/yfinance

- yfinance/__init__.py
Fixing dataframe indexing when some columns aren't present, defaulting values to NaN.
Existing error:
>>> yf.Ticker('SPY').option_chain( '2019-08-08' ) 
KeyError: "['openInterest'] not in index"
> Fixing dataframe indexing

- yfinance/__init__.py
New addition for sustainability data - very straightforward table to collect, however, as it has only a simple table with yes/no values, it should not try to deal with the extra numeric columns so a small fix is needed there which will make the get_fundamentals do less work as the table requires no processing.
Also mutual funds and ETFs have no financials, cash flow or balance sheet but it will cause an error to be thrown which is not gracefully handled such as by returning None or an empty list.
Note that pandas will require dependencies for (pip install) html5lib and BeautifulSoup4 before it throws this error since no HTML table is present.  Alternative is to from lxml import html, and use xpath('//table') == [] but try except seems more appropriate and less explicit dependencies …
> Add sustainability data/error handling for ETF/MF

- yfinance/__init__.py
Tested and working.
Try in current version (stock with no cash flow, financial or balance sheet data which is in the S&P500!):
tick = yf.Ticker('ABMD')
tick.cashflow()
Before, it will crash since it returns only the description column, and no data but there is still a table.
tick = yf.Ticker('VTI')
tick.cashflow()
will test the case for an ETF which has no table and gives ValueError.  These are 2 very common and easy to reproduce error scenarios (this latter one fixed in previous PR).
> Fix errors that can occur with partial data

- yfinance/__init__.py
Fix #105, default rounding to False is not ideal as generally expectation is correct price data.  Though this is a matter of opinion, it certainly seems from use cases that this is a poor default especially given the margin of error in the floats returned.
> Fix default rounding issue

- yfinance/base.py
new commits today seemed to break example code,
code run from colab, versions at the bottom
```
yf.__version__
msft = yf.Ticker("MSFT")
msft.info
hist = msft.history(period="max")
msft.actions
msft.dividends
msft.splits
msft.financials
msft.quarterly_financials
msft.balance_sheet
msft.quarterly_balance_sheet
msft.cashflow
msft.quarterly_cashflow
msft.earnings
msft.quarterly_earnings
msft.sustainability
msft.recommendations
msft.calendar
msft.options
```
```
/usr/local/lib/python3.6/dist-packages/pandas/core/ops/__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
result = method(y)
---------------------------------------------------------------------------
AttributeError …
```
> Bugfix, add _expirations to base

- yfinance/base.py
Fix for a bug I've noticed when you try to get info of a ticker without ESG scores
To reproduce using the latest version:
```python
ebro = yf.Ticker('EBRO.MC')
ebro.info
```
```python
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/alex-dev/.venv/<hidden>/lib/python3.8/site-packages/yfinance/ticker.py", line 122, in info
return self.get_info()
File "/Users/alex-dev/.venv/<hidden>/lib/python3.8/site-packages/yfinance/base.py", line 360, in get_info
self._get_fundamentals(proxy)
File "/Users/alex-dev/.venv/<hidden>/lib/python3.8/site-packages/yfinance/base.py", line 265, in _get_fundamentals
for item in data['esgScores']:
TypeError: 'NoneType' object is not iterable
```
> Fix empty esgScores

- yfinance/base.py
Currently there is no way to get the name of the stock or the market in which it operates. I've added to `Ticker.info` all properties from the `quoteType` object returned by Yahoo.
Here is an example of the `quoteType`.
```
{
"exchange": "NMS",
"shortName": "Tesla, Inc.",
"longName": "Tesla, Inc.",
"exchangeTimezoneName": "America/New_York",
"exchangeTimezoneShortName": "EDT",
"isEsgPopulated": True,
"gmtOffSetMilliseconds": "-14400000",
"underlyingSymbol": None,
"quoteType": "EQUITY",
"symbol": "TSLA",
"underlyingExchangeSymbol": None,
"headSymbol": None,
"messageBoardId": "finmb_27444752",
"uuid": "ec367bc4-f92c-397c-ac81-bf7b43cffaf7",
"market": "us_market"
}
```
> Add more data to info object

- yfinance/base.py
I saw that the ticker.info() method results in a Pandas DataFrame error for ticker symbols with list return values longer than 1 (e.g., AAPL returning a 'relatedControversy' key with a list of three values):
https://gist.github.com/liencis/df85238dba2b153f116053bde054a33d
Here I extended the existing filter for nested dictionaries on line 266 of base.py to also filter for the nested lists causing the errors:
https://gist.github.com/liencis/ccd378c095bdfc0212b6ac39a32cc926
> Fix pandas ValueError for lists in Ticker.info() method

- yfinance/base.py
This edit makes it possible to optionally suppress printing error messages to the console
in the history function by passing a named parameter "debug" in the **kwargs dict as False.
I made this to handle errors myself and prevent them from jamming up my console, because 
I'm using the console to pass data between two different programming languages and 
I can't have unintended messages flying around there. 
Thought that maybe others would also find this error message suppression feature useful.
> Suppress print error kwarg in def history

- README.rst
"stock" is not defined in the readme. the variable is called "msft".
> renamed stock to msft in readme

- yfinance/base.py
Rounding was described in comments as having a default of False, but the definition of the function has rounding set to True. Default in function definition was changed to False to stay consistent with comments
> Change rounding default in Ticker.history

- README.rst
- yfinance/ticker.py
Added note to README that datetimes are in UTC so people aren't confused. 
Also fixed options expiration date datetime into converting timestamp to UTC. It now matches the date specified on contractSymbol and the data on yahoo finance.
> Fixed Options Expiration Date and Added Datetime Note to README

- yfinance/base.py
As of now, the fetching of fundamentals is broken for some (all?) tickers (e.g. BIM.PA, AF.PA, IBM, etc.).
The reason for that is located in the `_get_fundamentals` method implemented in `base.py`, between the lines 280 and 285: the `url` var (containing the base_url and the ticker) has "/holders" appended, and when fetching the fundamentals, only "/financials" is appended again, instead of replacing "/holders".
This PR fixes the issue.
Before:
```python
yf.Ticker('BIM.PA').earnings
#=> Empty DataFrame
#=> Columns: [Open, High, Low, Close, Adj Close, Volume]
#=> Index: []
```
After:
```python
yf.Ticker('BIM.PA').financials
#=>          Revenue   Earnings
#=> Year
#=> 2016  2103200000  179100000
#=> 2017  2288200000  238100000
#=> 2018 …
```
> Fix the fetching of fundamentals

- README.rst
Fixing README.rst 'compatibility' typo (issue #504)
> Fix README.rst 'compatibility' typo

- yfinance/multi.py
Downloading ticker history with `proxy=True` while setting `thread=False` won't work due to the `proxy` parameter doesn't get propagated to the subroutine function. See [this issue comment](https://github.com/ranaroussi/yfinance/issues/66#issuecomment-565692359).
> Added missing proxy parameter

- yfinance/multi.py
`show_errors` argument added to `download` method with default value `True`.
`if show_errors == False` then errors **will not be printed.**
This is a fix for **Symbol Delisted** error printed if the data for that symbol is unavailable on Yahoo! Finance and discussed in #147
> [New Feature] Argument added for silencing error printing

- yfinance/base.py
If for some reason the `regularMarketOpen` value is not retrieved in the `summaryDetail`, then still attempt to retrieve the `regularMarketPrice`
Example ticker of where this happens is 'ETHI.AX', which does not have anything in the `summaryDetail`. It also has the following error
```
{'err': {'elapsedTime': 10,
'headers': {'age': '0',
'cache-control': 'max-age=0, private',
'content-length': '216',
'content-type': 'application/json;charset=utf-8',
'date': 'Wed, 16 Jun 2021 00:43:05 GMT',
'expires': '-1',
'server': 'envoy',
'vary': 'Origin',
'via': 'https/1.1 '
'media-router-api7007.prod.media.sg3.yahoo.com '
'(ApacheTrafficServer [cMsSf ])',
'x-envoy-upstream-service-time': '8',
'x-request-id': '2e424b2f-fb2b-447a-85b9-a09fc070c74f',
'x-yahoo-request-id': 'biaib19gcii8p',
'y-rid': …
```
> Get price even if open price not available

- yfinance/base.py
Holding a reference to an object (Requests in this case) as part of the
object's attributes prevents it from being serialized by Pickle.
This commit removes such module reference as part of yfinance
attributes.
Signed-off-by: Shay Agroskin <shayagr@amazon.com>
> Allow yfinance to be serialized by Pickle

- yfinance/base.py
Resolves an issue in base.py during historic retrieval of data.
In base.py history(), session.get can return None. Add an additional condition on line 190 of base.py has been added, which will throw a RuntimeError before the json parse exception can be thrown.
https://imgur.com/a/IgTqKah
> JSONDecodeError When Data is None 

- test_yfinance.py
- yfinance/base.py
- yfinance/ticker.py
- yfinance/utils.py
Before this commit there was no option to get the last 4 years' Shares Outstanding of a company. Now, this numbers can be found at the <code>Ticker.shares</code> attribute. Specifically, they refer to the average number of basic shares for each year.
> Make Historical Shares Outstanding number available (#892)

- test_yfinance.py
- yfinance/base.py
In base.py history(), session.get can return None or 404. Clarify exception catching within the history() method of base.py.
Ensure none and 404 values are caught prior to quote processing.
This prevents json parse exception, connection exception, or unbound exception from being thrown during data collection.
https://imgur.com/a/iXfZsvb
Includes updated unit testing.
> Resolves UnboundLocalError in base.py history()

- requirements.txt
- setup.py
Lock pandas version to fix AttributeError: 'Index' object has no attribute 'tz_localize' after pandas upgrade version to 1.4.0
Closes #937
> Fix: dev: AttributeError

- yfinance/utils.py
Explicitly set datetime index on actions df so that if the actions df is empty, it doesn't reset the index when combined with the rest of the dataframe. Closes #937. Credit to @ProgrammingDao
> Explicitly set datetime index on actions table

- yfinance/tickers.py
See issue: #677.
In order `Tickers()` to support cache like `Ticker()` doing, this patch makes it allow to pass `session` option arg.
Example:
```python
session = requests_cache.CachedSession('yfinance.cache', allowable_codes=(200, 401))
ts = yfinance.Tickers('GOOG MSFT', session=session)
for t in ts.tickers.values():
pprint.pp(t.info)
```
> Support cache in `Tickers()`

- yfinance/base.py
When attempting to retrieve the maximum period of time (period="max") at 1 minute intervals, the previous default start period of 1900-01-01 (631159200) would result in an error from the API with description "1m data not available for startTime=*START TIME OF PRICE HISTORY* and endTime=*NOW*. Only 7 days worth of 1m granularity data are allowed to be fetched per request." . By setting the start time to the end time minus 604800 (86400*7) when the interval="1m", it now returns 1 week of 1 minute interval data which is the maximum period for which the API supports at 1 minute intervals.
> Fixed max period when interval is 1 minute

- yfinance/base.py
Re: #724 
Seems that yahoo gives incorrect key as 'treasuryStock'. 
If check Treasure Stock Data on zacks.com, it must be 0 values for MSFT:
https://www.zacks.com/stock/quote/MSFT/balance-sheet
If recheck with marketbeat.com, these values match values of "Accumulated Other Comprehensive Income":
https://www.marketbeat.com/stocks/NASDAQ/MSFT/financials/
On the other hand self yahoo web calls these values now as 'Gains Losses Not Affecting Retained Earnings':
https://finance.yahoo.com/quote/MSFT/balance-sheet?p=MSFT
Renaming key 'treasuryStock to yahoo's "Accumulated Other Comprehensive Income" in data will help to avoid confusion
> rename incorrect yahoo key treasuryStock

- yfinance/base.py
Before this commit, if the API returned no shares' data of a ticker for one or more years, the <code>shares</code> attribute of <code>Ticker</code> returned None. Now, it returns the shares data for the available years.
> Handle case that the API returns no data for shares of a specific year (#999)

- yfinance/base.py
When running `Ticker()` many times the init time is significant. Caused by `utils.empty_df()` calls, but these can be moved out into `get_fundamentals()`. Reduces runtime of 1000 calls from seconds to milliseconds, doesn't affect fundamentals.
> Ticker.init() perf boost

- yfinance/base.py
- yfinance/multi.py
Keeping NaNs rows returned by Yahoo may be useful because the timepoints are still valid so provides list of trading intervals.
New argument `keepna=False` controls whether to keep/drop these NaN rows.
#1028 relevant
> Add 'keepna' argument

- yfinance/base.py
I was playing with 15m data which is created internally from 30m data - the price-after-end-date bug (https://github.com/ranaroussi/yfinance/pull/1026) was messing with the 15m->30 conversion. So just moving the bug-fix up in code.
I also snuck in a timezone fix: `fromtimestamp()` -> `utcfromtimestamp()`
> Bugfix: Relocate out-of-range check to before 15m->30m conversion

- yfinance/base.py
- yfinance/utils.py
This big update fixes all problems related to timezones:
1. Convert Yahoo datetimes from UTC into timezone of exchange [#978](https://github.com/ranaroussi/yfinance/issues/978) [#1010](https://github.com/ranaroussi/yfinance/issues/1010)
2. If user provided timezone-naive datetimes then assume they mean timezone of exchange [#1010](https://github.com/ranaroussi/yfinance/issues/1010)
3. Use `datetime` module for epoch read/write instead of `time` [#954](https://github.com/ranaroussi/yfinance/issues/954) [#949](https://github.com/ranaroussi/yfinance/issues/949)
4. Yahoo can mess up DST so day start time is off by an hour - e.g. Brazil around Jan-2022 is 23:00 instead of 00:00. So detect and adjust to 00:00
5. Process user-provided `tz` argument correctly - use it to convert, not localize …
> Fix timezone & datetime handling

- README.md
- yfinance/multi.py
Recent timezone fixes changed download() behaviour - multi-timezone data stopped aligning neatly. Solution = allow user to ignore timezones.
> Add 'ignore_tz' arg to download()

- yfinance/base.py
If localizing a midnight during DST transition hour when clocks roll back, where clock hits midnight twice, then use the 2nd hit.
Fix issue #1100
> Fix tz-localize when DST-ambiguous

- tests/prices.py
- yfinance/base.py
- yfinance/utils.py
Various fixes to price data:
- add timezone to daily data index
- fix `Ticker.dividends` property
- stop `dropna` dropping pre-market dividend events
Several fixes to events merging for (i) weekly and (ii) intra-day. And add a test for this.
> Various fixes to price data

- yfinance/base.py
- yfinance/utils.py
Instead of doing homegrown caching using CSV files and having to handle tricky concurrency issues use built in python module SQLite (simple SQL-database) for the ticker/timezone-cache.
Hopefully this should lead to less issues and better performance.
I did some performance tests and on my machine (*) adding 1000 tickers and reading them back took 1s. And 2:nd run when they did not need to be added to cache it took 100ms.
Also did some test with running concurrent python scripts reading/writing the same db and it seems to work well.
* Windows 10, Python 3.8 AMD Ryzen 5 3600 and SSD)
```
def main():
res_list = []
for i in range(1000):
k = f"key_{i}"
v = f"val_{i}"
res = tz_db.get(k)
if not res:
tz_db.set(k, v)
res_list.append(tz_db.get(k))
return res_list
if __name__ == '__main__':
start = …
```
> Fix and improve timezone cache concurrency

- README.md
- yfinance/__init__.py
- yfinance/base.py
- yfinance/utils.py
Silently handle errors in the timezone-cache without stopping execution.
Add `set_tz_cache_location()` so user can provide alternative location, in case default not accessible.
Resolves issue #1107
> Fix cache error on read only system

- yfinance/base.py
- yfinance/utils.py
Make sure to only do 1 call to self.info and simplified the code but retaining the logic.
> Fix for #1076

- README.md
- tests/prices.py
- yfinance/base.py
- yfinance/multi.py
- yfinance/tickers.py
- yfinance/utils.py
Yahoo sometimes returns random prices 100x correct value. Only seen in London tickers, typically weekly data. Looks like Yahoo is mixing up currency units £ and pence. See issue #552 for detail.
Solution uses a `scipy` module to find these outliers. For Open/Close divide by 100, simple. For High/Low must recalculate because corrupted - 100 x low = new high. Recalculation fetches data at next resolution, e.g. if repairing weekly data fetch daily data for that week. Potential to trigger Yahoo spam detection, but normally only few outliers in a year of data so not expecting to trigger.
Deliberately not adding scipy to dependencies, assuming most users won't use this feature.
> Feature - repair 100x price errors

- tests/ticker.py
- yfinance/base.py
- yfinance/multi.py
- yfinance/tickers.py
Instead of fetching and building `info`, just fetch basic price data which contains timezone. ~1.7x speedup. Hopefully also reduces failures to get timezone (issue #1076)
> Improve performance of fetching Ticker timezone

- yfinance/base.py
Hi.
This is a very helpful project. I noticed that when no website exists on the info, the logo url is not generated. I add a little change that in this case uses the small name that allways is present.
I think this could help with this Issue:
yfinance info logo_url value problem #1062
> Bugfix: Get logo url when no website exists

- yfinance/base.py
Resolve #1114, which was caused by redundant code so just removed it.
Move the logic into `_get_info()` - I introduced this bug in my big timezone update (#1048), so 'trailingPegRatio' would have disappeared from `info[]`.
Simplify the code as loop is unnecessary. Also disable it, replacing with a direct GET - scraping a whole page for one variable is a waste. Keep the original code in case do want all key statistics in future.
@rickturner2001 I believe you first requested that 'trailingPegRatio' be fixed (#903).
> Move get 'trailingPegRatio' into _get_info(), simplify & optimise

- test_yfinance.py
- yfinance/base.py
Fix #1096 (again), and add more tests to be sure!
> Improve handling delisted tickers

- tests/prices.py
- yfinance/base.py
- yfinance/utils.py
In the reordering of quotes processing (base.py#L297) I had accidentally disabled 2x Yahoo bug fixes:
- Yahoo messing up DST
- Yahoo returning weekly/monthly data across 2 rows
Now enabled, with tests to be sure.
> Fix the fixes for Yahoo data issues (DST, weekly-2-rows) + tests

- yfinance/utils.py
Somehow additional ',' were appearing in ticker tz csv, i.e. adding more than 2 columns (issue #1158), generating an exception:
> pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields saw 3
Fix = silently discard corrupt csv rows.
> Fix corrupt tkr-tz-csv halting code

- tests/ticker.py
- yfinance/base.py
- yfinance/data.py
The wrong data was returned for balance_sheet and cashflow
> Fix fundamentals regression bug

- yfinance/base.py
- yfinance/multi.py
`debug_mode` was not correctly disabled during threaded execution, causing bpython interpreter to deadlock. Fixes #1096
> Fix disable prints inside threads (bpython deadlock)

- yfinance/multi.py
Needed as current thead implementation breaks if exception is raised.
> Add glob try/except in threaded implementation.

- README.md
- tests/ticker.py
- yfinance/base.py
- yfinance/ticker.py
Avoid unnecessary request when fetching earnings_date. Added support to limit argument to only fetch as many as needed.
> Made fetching earnings_dates faster

- README.md
- Typos in variable name
- `Ticker` doesn't support several tickers
- `Tickers` doesn't return named tuple
- "1m" in `download` would produce an error for longer timeframes, so changing the example to "5d"
> Fix a couple of minor issues in README

- tests/prices.py
- yfinance/utils.py
Extend Yahoo duplication fix to intra-data price data e.g. 1H.
> Extend Yahoo duplication fix to intra-day

- README.md
- tests/ticker.py
- yfinance/ticker.py
Change financials `pretty` format default to `True` to match historic behaviour. But I also added a note to README that other formats available, so hopefully both groups of users are happy.
> Default enable 'pretty' financials, explain in README

- README.md
- tests/ticker.py
- yfinance/base.py
- yfinance/scrapers/fundamentals.py
For some tickers Yahoo does not display quarterly financials. I notice most with Australian tickers e.g. BSE.AX . https://finance.yahoo.com/quote/BSE.AX/cash-flow?p=BSE.AX
This means `yfinance` using the TimeSeries API also returns an empty table. But the old-style table is still present in QuoteTimeSeriesStore, so I propose returning this. Question - should user be alerted to switch? How?
@git-shogg
> Serve old financials when new financials are missing

- tests/ticker.py
- yfinance/base.py
- yfinance/data.py
- yfinance/scrapers/fundamentals.py
- yfinance/scrapers/holders.py
- yfinance/scrapers/quote.py
`data` was being used to cache all price history requests, when only past date ranges should be cached (end < now).  To fix: restored original `get()` function and created new `cache_get()` wrapper with LRU decorators.
Also fixed some session issues in unit test `test_no_expensive_calls_introduced`
> If fetching price history ending in future, don't use cache

- README.md
- meta.yaml
- requirements.txt
- setup.py
#1231 incorrectly removed `lxml` dependency. This PR restores it, but raises minimum version to 4.9.1 to fix #1211.
> Restore lxml dep, set min ver = 4.9.1

- README.md
- tests/ticker.py
- yfinance/base.py
- yfinance/ticker.py
Here's the PR for `history_metadata`.
- See also https://github.com/ranaroussi/yfinance/issues/1195.
- I ended up calling it `history_metadata` after all rather than `exchange_metadata` because it not only includes exchange-related information (e.g., `currency`, `symbol`, `instrumentType`).
- Also, this is a new PR. The old one at https://github.com/ranaroussi/yfinance/pull/1198 can be closed.
(BTW, is it just me or is the code base pretty messy? For example, type hints are very inconsistent. And what is the purpose of `TickerBase` vs `Ticker` class?)
> Add `history_metadata` property

- README.md
- meta.yaml
- requirements.txt
- setup.py
- yfinance/utils.py
Backport of #1253 (credits to @Rogach & @fredrik-corneliusson). Until can decide which of `cryptography` or `pycryptodome` to use, include both in the code but defaulting to `cryptography` because *slightly* faster.
> Backport Yahoo decryption

- README.md
- meta.yaml
- requirements.txt
- setup.py
- yfinance/data.py
WIP decryption code for issue #1246 
~~However this doesn't fix the issue completely, since QuoteSummaryStore is not found in the decrypted data - probably the data is now stored in some other place.~~
> decode encrypted root.App.main.context.dispatcher.stores

- yfinance/base.py
If ticker lacked `_sustainability` or `_recommendations` because Yahoo lacked, was causing `info[]` to be recreated every call.
> Another info[] fix for #1256

- yfinance/utils.py
As per discussion in #1274, initialize the database in constructor to avoid database lock error in multithread environment.
> Fix the database lock error in multithread download

- README.md
- yfinance/multi.py
With #1093, setting `ignore_tz=True` makes `download()` behave differently to previous version. This PR sets ignore_tz to False by default to bring the behavior of download() to be the same as 0.1.77 and prior.
Fixes #1275.
> Change default value to ignore_tz to False

- yfinance/scrapers/fundamentals.py
- yfinance/scrapers/quote.py
- Replace 'datetime.now()' with midnight
Some financial data was being fetched using parameters derived from `datetime.now()`, so obviously will never get reused in `requests_cache`. Replace with midnight
Originally proposed in PR #1204 alongside a controversial change, so separated out for quicker merge.
> Improve caching of financials data

- yfinance/data.py
> Fix stores decrypt

- README.md
- tests/ticker.py
- yfinance/base.py
- yfinance/scrapers/quote.py
- yfinance/ticker.py
- yfinance/utils.py
Draft implementation for #1300 so feedback wanted. See that Issue for discussion of why ...
`Ticker.basic_info` provides fast access to ~25 values of `Ticker.info[]`, e.g. last close price. To encourage users to switch, these keys are removed from `info`. If user is using affected keys, then `yfinance` will print migration instructions eg:
`dat.info["open"]`
> Price data removed from info. Use Ticker.basic_info or history() instead
> `Ticker.basic_info` - fast but minimal alternative to `info[]`

- yfinance/data.py
They just added a new key. Added it to the list, commented exception, the thing works now:
https://gist.github.com/ifel/5cdbf537a79da8a6e37203b1a9c30e4f
> Add new yahoo key

- yfinance/data.py
Should fix #1329
Thanks @ifel #1335
> Hardcode decryption keys

- yfinance/base.py
Fixes #1340 
`Ticker.basic_info.keys()` was calling each method. Defeats lazy-loading, and raised exceptions for tickers without share count (e.g. FX)
> Fix 'Ticker.basic_info' lazy-loading

- tests/ticker.py
- yfinance/base.py
- yfinance/scrapers/quote.py
Name `basic_info` was misleading users of purpose (see later discussion in #1300). `fast_info` should convey better.
Also fixed some info test issues.
Clarify "no share count" error handling.
> Rename 'basic_info' -> 'fast_info'

- tests/ticker.py
- yfinance/base.py
- yfinance/ticker.py
- yfinance/utils.py
`fast_info` usability improvements:
- Add support camelCase dict keys, and officially support these, but secretly continue to also support snake_case keys
- Add `dict` functions `values()` and `items()`
> `fast_info` usability improvements

- tests/prices.py
- yfinance/base.py
- yfinance/utils.py
When requesting intraday price data with `prepost=False`, sometimes Yahoo returns an interval at regular market close. Normally happens on half-day early closes. Can get market close datetimes from `history_metadata` so easy to fix.
> Drop intraday intervals if in post-market but prepost=False

- tests/ticker.py
- yfinance/base.py
- yfinance/scrapers/quote.py
`history(interval="1d", prepost=True)`  is unreliable. Yahoo sometimes missing daily data (e.g. 'SOKE.IS'), or prices don't include prepost. Solution = use `interval="1h"` instead. Fixes #1381
Also adjusted 'yearChange'
> Fix fast_info["previousClose"]

- yfinance/utils.py
"without rowid" requires sqlite 3.8.2, lder versions will raise exception. But this feature isn't necessary so disable if old.
Fixes #1372
> Allow using sqlite3 < 3.8.2

- yfinance/base.py
Error: "Yahoo web request for share count failed"  updated cache_get call by adding proxy parameter and by calling it by keyword
> get_shares_full does not work with proxy

- yfinance/multi.py
`download()` original behaviour for handling timezones of different exchanges depended on interval:
- intraday = keep timezones
- interday = ignore timezones
This was lost with #1048 but no one noticed for long time. It treated all intervals same way - never ignore. Eventually users noticed and requested always ignore #1103, then never ignore again #1283.
@DE0CH
> Restore original download() timezone handling

- tests/ticker.py
- yfinance/base.py
- yfinance/utils.py
Fix format_history_metadata when firstTradeDate is None, as is the case for QCSTIX and probably others.  Submitting this on main since it seemed appropriate for that based on the instructions in https://github.com/ranaroussi/yfinance/discussions/1084 -- I can redo it if that is not what you want.
> Fix `history_metadata` accesses for unusual symbols

- yfinance/data.py
- yfinance/scrapers/quote.py
Due to the persistent failure of info property of Tickers due to decryption error of yahoo finance web pages, I added a failback to get some information from unofficial api https://query1.finance.yahoo.com/v7/finance/quote. which can get the ticker short/long name, listed date, exchange, timezone etc.
Quick test
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import yfinance as yf
>>> ticker = yf.Ticker("KWEB")
>>> ticker.history()
Open       High        Low      Close    Volume  Dividends  Stock Splits  Capital Gains
Date
2023-02-23 00:00:00-05:00  31.150000  31.170000  29.785000  30.030001  21059600        0.0           0.0            0.0
2023-02-24 00:00:00-05:00  29.040001  29.350000  28.670000  28.910000  24900400        0.0           0.0            0.0 …
```
> Fetch 'info' dict from API instead of scraping

- yfinance/base.py
tzinfo does not have a localize attribute so it is replaced with timestamp in UTC
> Fix tzinfo missing attribute

- yfinance/utils.py
> Fix handling Pandas parsing error during TZ-csv-cache migrate

- yfinance/utils.py
Fixes #1321 - `IntegrityError('NOT NULL constraint failed: kv.key')` when migrating timezone CSV cache to sqlite
> Fix timezone cache error: IntegrityError('NOT NULL constraint failed: kv.key')

- yfinance/base.py
- yfinance/utils.py
`format_history_metadata()` is expensive. Improvements:
- only perform full formatting if user requests metadata
- when pruning prepost data, only format 'tradingPeriods' entry of metadata
Other small optimisations to several internal prices processing methods.
Speedups (excluding web fetch time):
`dat.history(period='1wk', interval='1h', prepost=True)`  2x 
`dat.history(period='1mo', interval='1h', prepost=True)`  1.46x 
`dat.history(period='1wk', interval='1h')`  1.15x
`dat.history(period='1mo', interval='1h')`  1.13x
`dat.history(period='1y', interval='1d')`  1.36x
`dat.history(period='5y', interval='1d')`  1.13x
> Optimise Ticker.history() - up to 2x faster

- yfinance/base.py
- yfinance/scrapers/quote.py
Improve logging messages related to price data fetches:
- fix 'debug is deprecated' msg
- append user args to 'may be delisted' msg - interval & dates/period
- improve formatting of 'cannot reconstruct' msg
- hide errors in `history()` while accessing `fast_info[]`
> Improve logging messages

- yfinance/utils.py
When discarding corrupt data from old CSV-cache, was checking second column but not first column aka index. Now check both columns. Fixes #1526
> Fix corrupt tkr-tz-csv halting code (again)

- tests/context.py
- tests/prices.py
- tests/ticker.py
- yfinance/multi.py
- yfinance/scrapers/quote.py
New logging in `download` stores the tracebacks, but the logic was faulty, this fixes that. Also improves error handling in `download`.
Unit tests should have detected this so improved them:
- add/improve `download` tests
- disable tests that require Yahoo decryption (because is broken)
- fix logging-related errors
- improve session use
Fixes #1539
> Bugfix in `download` logging tracebacks & boost tests

- yfinance/multi.py
Allows user to pass a session object to the download method.
Fixes [#1534](https://github.com/ranaroussi/yfinance/issues/1534)
> add session to download

- yfinance/utils.py
Fix for exception using `_pd.Timedelta()` function with `unit='d'` parameter for  Pandas v1.4.4. Just removed the parameter as it was unnecessary.
> Fix timedelta bug

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- yfinance/__init__.py
- yfinance/base.py
- yfinance/data.py
- yfinance/multi.py
- yfinance/scrapers/analysis.py
- yfinance/scrapers/fundamentals.py
- yfinance/scrapers/quote.py
- yfinance/utils.py
Various changes to improve alignment of logging output, particularly DEBUG logs.
`MultiLineFormatter` improves appearance of multi-line messages in any logging mode. Adds leading indent to all lines below first, to align with the first line which is indented by %levelname%.
Only add stream handler if no root logger, this fixes message being double-printed.
Then specifically for DEBUG logs:
1 - Whitespace padding is added to end of %levelname% string up to 8 characters. This resolves different level strings e.g. INFO & DEBUG creating different indents. But this only automatically applies to first line of message - for multi-line messages, `MultiLineFormatter` extracts amount of padding and applies to all other lines.
2 - Add leading indent proportional to function depth, because DEBUG …
> Fix logging behaviour

- yfinance/utils.py
... also move '_TzCacheException' logging from level ERROR to INFO, because users don't need to know.
Fixes #1573
> Fix unhandled 'sqlite3.DatabaseError'

- .gitignore
- yfinance/base.py
> ticker.basic_info["last_price"]
sometimes raises:
GDEVW: 1d data not available for startTime=-2208994789 and endTime=1687780922. Only 100 years worth of day granularity data are allowed to be fetched per request.
> fix start date on history

- README.md
The example in the docs will not work out of the box due to a syntax error.
> fix: Readme cache-ratelimit. Limiter parenthesis was never closed

- yfinance/multi.py
Fix #1525, #898.
I am submitting this directly to main since this bug is already in production.
> [BUG] Fix failure when using single ISIN as a ticker (#1525)

- README.md
- meta.yaml
- requirements.txt
- setup.py
As suggested in #1616. I messed up something here and reverted the whole thing.
- Bumps requests to 2.31
- Removes cryptography (unnecessary)
> Bump requests to 2.31 and removes cryptography.

- tests/prices.py
- Adjusted prices.py according to PEP 8 coding style suggestions, except:
- E501 line too long
- E701 multiple statements in one line
- Changed tkr_div_dates declaration/assignment style within TestPriceHistory::test_dailyWithEvents (this is the only thing non-PEP8 here)
> Adjust PEP 8 + minor improvement

- tests/prices.py
- yfinance/base.py
As per discussed in #1624.
- `prices.py`: minor correction 
- `base.py`: 
- multiple PEP 8 adjustments (ignoring E702 and E501)
- removal of old .format-styled strings
----
In [`base.py:867`](https://github.com/ranaroussi/yfinance/blob/dev/yfinance/base.py#L867) there is an import mid-code that I have preserved; not sure what to do with it since it is conflicting with the comment right above it:
```python
from scipy import ndimage as _ndimage
```
If this is handled by some other PR, or if I should just ignore this for now, please let me know.
There are a few other issues with this file, but for the sake of organization, I will submit a future issue/PR touching these other warnings/errors.
> Adjust PEP 8 + minor improvements + f-strings in base.py

- yfinance/ticker.py
options_chain() return underlying data that comes with the options data.  this is helpful to ensure that underlying bid,ask,trade and options bid,ask,trade are in sync, plus avoids an additional call since the data comes from the options chain request anyway.
> option_chain() return underlying data that comes with the options data

- yfinance/utils.py
Retrieving quotes by indexes but not using pandas `iloc` method, which show a warning:
```
FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
if not _np.isnan(quotes["High"][n - 1]):
```
- Modified yfinance/utils.py to fix an issue with retrieving live data from Yahoo Finance.
- Replaced the use of square brackets with the `iloc` method to access specific elements in the DataFrame.
- Updated the code to use `iloc` instead of indexing with column names.
> Fix pandas warning when retrieving quotes.

- README.md
- meta.yaml
- requirements.txt
- setup.py
- yfinance/utils.py
Fix bug #1674. Turns out the timezone cache was never fully thread-safe.
> Replace sqlite3 with peewee for 100% thread-safety

- yfinance/utils.py
When call `enable_debug_mode` twice, It makes error.
```
Traceback (most recent call last):
File "/home/arduinocc04/Documents/GitHub/yfinance/test_yfinance.py", line 75, in <module>
yf.enable_debug_mode()
File "/home/arduinocc04/Documents/GitHub/yfinance/yfinance/utils.py", line 185, in enable_debug_mode
setup_debug_formatting()
File "/home/arduinocc04/Documents/GitHub/yfinance/yfinance/utils.py", line 172, in setup_debug_formatting
if yf_logger.handlers is None or len(yf_logger.handlers) == 0:
^^^^^^^^^^^^^^^^^^
AttributeError: 'IndentLoggerAdapter' object has no attribute 'handlers'. Did you mean: 'hasHandlers'?
```
This error is so annoying when using jupyter and rerun code block.
> Fix error when calling enable_debug_mode twice

- tests/prices.py
- yfinance/utils.py
If Yahoo returns intraday price data with dividend or stock-split event in future, then this broke the merge. Fix is to discard out-of-range events.
Assumes that if user requesting intraday then they aren't interested in events.
> Fix merging events with intraday prices

- yfinance/base.py
Preparing several fixes to price repair.
Will do this message properly (and squash) when (i) pushed all fixes and (ii) tested a little more.
> Price repair fixes

- tests/context.py
- yfinance/utils.py
Fix #1694 
Also refactored timezone caching, and improve testing to detect cache folder issues.
> Fix: OperationalError('unable to open database file')

- tests/ticker.py
- tests/utils.py
- yfinance/utils.py
Hopefully fix TZ cache exception blocking import #1700
The Singleton pattern makes unit testing this tricky, so can someone affected try branch? @rickturner2001 
Also:
- relocate cache init lock
- add test for setTzCacheLocation()
> Fix TZ cache exception blocking import

- tests/ticker.py
- yfinance/base.py
- yfinance/scrapers/holders.py
This addresses #1685 (`institutional_holders`) and also `get_earnings_dates()`.
Pandas issue is found here:
https://github.com/pandas-dev/pandas/issues/53767
and the change in code here:
https://github.com/pandas-dev/pandas/blob/5cedf87cccd77c7b4b6aaa64bfec98b32b512f68/pandas/io/html.py#L1238
As for legacy Python 2.7 support: `io.StringIO` seems to be supported in the versions I tested. See https://docs.python.org/2/library/io.html
> Fix pandas FutureWarning: "Passing literal html to 'read_html' is deprecated"

- yfinance/data.py
`_set_cookie_strategy` was flipping strategy twice - `basic` -> `CSRF` -> `basic` - so no effect.
Might fix #1744
> Fix '_set_cookie_strategy'

- tests/ticker.py
- yfinance/base.py
Fixes #1739 : 
- FutureWarning deprecation warning for pandas resolved by updating fillna and iloc in the `reconstruct_intervals_batch` function.
- Added a unit test to tests/ticker.py in TestTickerHistory called `test_reconstruct_intervals_batch`, also validated against current output.
> Pandas future proofing

- tests/prices.py
- yfinance/multi.py
This is to address Issue #1743 
This PR has a simple one line fix where I convert the time column from an Index.base type to a datetime object in the download function (in multi.py). 
This error was occurring due to the pd.concat function and how it handles empty dataframes. 
I also added a unit test for this based off of the issue.
> Fix for Key Error Issue on Date column when one of the symbols is no longer valid (delisted/not available)

- yfinance/utils.py
This PR is to address issue #444
> Moved progress bar output to stderr

- tests/ticker.py
- yfinance/scrapers/quote.py
This PR is meant to fix #1305. The old version of the code incorrectly checked for the "trailingPegRatio" complementary statistic which caused the data associated with that key to always be None. The parsing for this key has been fixed and the scheme has been modified to allow for other complementary stats to seamlessly be added to the "keys" dictionary.
A test case has been added to verify that this statistic is properly being retrieved.
> Fixed incorrect code for ticker complementary info retrieval

- yfinance/cache.py
`peewee.DateTimeField` is not ISO-compliant. If user enforces strict ISO-compliance, then translation between DateTimeField and sqlite breaks. Fix is to manually implement translation.
Fix #1748
> Fix invalid date entering cache DB

- yfinance/base.py
/usr/local/lib/python3.9/site-packages/yfinance/base.py:2126: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'NaN' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
dates.loc[dates[cn] == '-', cn] = "NaN"
> make nan as float

- setup.py
Set sensible minimum versions for optional `nospam` reqs:
- requests_cache >= 1.0 , first defined `DO_NOT_CACHE` - resolve #1751
> Set sensible min versions for optional 'nospam' reqs

- yfinance/base.py
I'd like to be able to handle any exception that might happen while `Ticker.history()` performs the HTTP request.
I currently do it in a hackish way using a monkey patch.
With this PR I'd like to introduce a hook for a custom function that, when given, it is invoked when such exception happens.
Most basic example I can think of:
```py
import requests
from pandas import DataFrame
def reraise(exc):
raise exc
ticker = yf.Ticker("AAPL")
try:
data: DataFrame = ticker.history(
interval="1m",
start=...,
end=...,
timeout=10,
raise_errors=True,
request_exc_hook=reraise,
)
except requests.ConnectTimeout as exc:
...
```
Note that my actual case a bit more complex to explain and boring (meaning not really useful for this proposal).
> Ticker.history() to raise HTTP request excs if raise_errors args is True

- yfinance/base.py
The exception was something like "Unalignable index" or "Size mismatch" during price repair, on line #730 in `base.py`. This fixes that.
> Fix price repair div adjust

- yfinance/multi.py
This pull request is related to an edge case posted on Stack Overflow (https://stackoverflow.com/q/74835912/19123103) whose cause was that when data for multiple tickers is downloaded, the column levels did not have names. This pull request edits the call to `pandas.concat()` by passing level names ('Ticker' and `Price`) to it.
So a call such as 
```python
df = yf.download("GOOGL,AMZN", start='2023-12-01', end='2023-12-07')
```
will produce
```none
Price        Adj Close                   Close                    High  
Ticker            AMZN       GOOGL        AMZN       GOOGL        AMZN   
Date                                                                     
2023-12-01  147.029999  131.860001  147.029999  131.860001  147.250000   
2023-12-04  144.839996 …
```
> explicitly name the column levels

- README.md
Wrap yfinance[optional] code snippet with quotes to avoid conflict with zsh globbing. Remains compatible with bash.
> Update README.md for better copy-ability

- yfinance/base.py
The repair column was blocking dropping of NaN prices.
> Fix history() keepna=False with repair=True

- yfinance/cache.py
Hopefully fix #1825. That `peewee` error looks same as old `sqlite` error #1380, so fix assumed same conceptually.
> Handle peewee with old sqlite

- yfinance/base.py
Fix to prevent KeyError on 'timeseries'. 
If requested symbol is incorrect/null, Yahoo Finance API returns this response : 
```
{'finance': {'result': None, 'error': {'code': 'Not Found', 'description': 'HTTP 404 Not Found'}}} 
```
Hence raising a KeyError exception instead of the YFinanceException one, with an explicit error message.
You can re-create the case this PR fixes by trying an incorrect ISIN code, e.g. ` yf.Ticker("FR0000000000").info `
> Fix JSON error handling

- yfinance/scrapers/history.py
Seems like some typos or part of the code never been hit before.
df and df2 must be same shape.
pd.to_datetime() had no argument?
```python
yf.Ticker('rshn').history(start='2000-01-01', end='2024-02-18', repair=True, auto_adjust=True, actions=True)
File ~/anaconda3/envs/3.11/lib/python3.11/site-packages/pandas/core/indexing.py:1414, in _LocIndexer._getitem_axis(self, key, axis)
1412     return self._get_slice_axis(key, axis=axis)
1413 elif com.is_bool_indexer(key):
-> 1414     return self._getbool_axis(key, axis=axis)
1415 elif is_list_like_indexer(key):
1416     # an iterable multi-selection
1417     if not (isinstance(key, tuple) and isinstance(labels, MultiIndex)):
File ~/anaconda3/envs/3.11/lib/python3.11/site-packages/pandas/core/indexing.py:1210, in …
```
> Fix some errors.

- README.md
- yfinance/__init__.py
- yfinance/multi.py
Drop official support for 'pandas_datareader', tag pdr_override() as deprecated. Implements #1192.
Also removed deprecated argument 'download(show_errors)'.
> Deprecate 'pandas_datareader', remove a deprecated argument

- yfinance/scrapers/holders.py
Fix for the issue #1904, the ticker symbol has been moved from the parameters to the end of the base URL.
> Fix 404 Error for Holders

- yfinance/utils.py
Fix for the issue #1909. The functools.wraps function has been added to the log_indent_decorator's wrapper function. This way ``help(yf.download)`` will appropriately show the docstring for ``yf.download``.
> Fix help(yf.download) not showing the information about the function

- yfinance/data.py
Session switch logic was not recalculating `self._session_is_caching`.
Also removed message "help stress-test cookie & crumb & requests_cache", clearly works now.
> Fix switching session from/to requests_cache

- yfinance/scrapers/history.py
Original logic for repairing missing split adjustment only checked latest split.
Improved logic checks ALL splits in data, because any can be missing.
Then related changes to 'sudden change detection':
- use prices median not mean, reduce sensitivity to noise.
- handle Kuwait Dinar, which sub-divides into 1000x not 100x (fix #1937)
>  Price repair: improve 'sudden change' repair for splits & currency 

- yfinance/scrapers/history.py
site-packages/yfinance/scrapers/history.py:239: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
> Fix 'T' is deprecated

- yfinance/__init__.py
- yfinance/base.py
- yfinance/scrapers/fundamentals.py
- yfinance/scrapers/quote.py
The earnings chart on Yahoo website not available directly via API, have to get from income statement. Resolve #1948 
Also remove some old deprecated code.
> Deprecate Ticker.earnings

- yfinance/scrapers/history.py
Was debugging my code today and it appears that all of the `possibly delisted` errors were being printed twice, once from the logger and once from this print statement. You're already logging any errors, so this print statement doesn't need to be here.
Closes #1997
> Remove erroneous print statement

- yfinance/ticker.py
Fixes #1969 
Error occurs when Yahoo has no calls or puts for a ticker. I wasn't sure whether y'all would prefer an exception in this case instead (first pull request!), but I chose to return an "empty" Options namedtuple since _download_options() returns an empty dict.
> Fix error on empty options chain

- README.md
- yfinance/base.py
- yfinance/scrapers/quote.py
- yfinance/ticker.py
Implement #2007 . @dmoklaf give feedback - can structure be improved more? How do you use the data?
> Implement fetch sec-filings

- yfinance/scrapers/holders.py
- using dict.get() is safer than dict[key] and allows effective way to return non-`None` variable
- Fixes https://github.com/ranaroussi/yfinance/issues/1940:
Sample Checks:
```python
ticker = yf.Ticker('AACG') # from the attached major_holders.not.found_0-1.txt
print(ticker.major_holders)
```
```txt
Breakdown                        Value
insidersPercentHeld            0.07085
institutionsPercentHeld        0.16265
institutionsFloatPercentHeld   0.17506
institutionsCount             12.00000
```
```python
ticker = yf.Ticker('RVSN') # from the attached major_holders.not.found_4-5.txt
print(ticker.major_holders)
```
```txt
Breakdown                        Value
insidersPercentHeld            0.38820
institutionsPercentHeld        0.02128
institutionsFloatPercentHeld   0.03478 …
```
> use dict.get() to safely access key in Holders

- yfinance/exceptions.py
- yfinance/scrapers/history.py
- yfinance/utils.py
> Prices: improve exceptions and logging

- yfinance/base.py
- Fixes: https://github.com/ranaroussi/yfinance/issues/2015
- The trace provided in the issue shows the exception occurs due to trying to parse faulty response object `JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
- try except catches the error and returns empty set instead of raising the exception. 
- The error is logged and the API user sees empty list of news instead of the raised exception.
- Add check if returned value is None before accessing its text to avoid AttributeError
> Handle faulty response object when getting news.

- tests/test_prices.py
- tests/test_utils.py
- yfinance/multi.py
When querying multi symbols at the same time, the Pandas Timestamp to datetime64 conversion will fail, when `utc=False`.
It looks like this is the most stable implementation, because Pandas suggests to use this feature in the future.
Downside: The original timezones are lost. But every datetime has now `tz=timezone.utc`
Upside: `ignore_tz` may be obsolete.
I added a test for testing Pandas datetime conversion as well.
> Fix datetime conversion with mixed timezones when ignore_tz is False

- yfinance/scrapers/history.py
Solution that checks the offset of the opening time of the stock exchange (mod 30 minutes) and adds it to the quotes
That issue addresses  #1436 and #1447.
-----------
The only change lies in `yfinance/scrapers/history.py`. 
If ìnterval='30m'`, we find the time that the stock exchange opens. If it opens at a time `t.minutes % 30 != 0` we add that offset to the quote.
> Solves #2026 

- README.md
- tests/test_ticker.py
- yfinance/base.py
- yfinance/scrapers/analysis.py
- yfinance/ticker.py
I implemented most of the analysis page (https://finance.yahoo.com/quote/AAPL/analysis/). As the URL suggests, analysis is just a part of the `quoteSummary` API endpoint, which means all the data can be fetched from there. I saw some attempts at scraping the data (#1668 #1778), but that can be  inefficient and slower.
I was trying to follow the table layouts on the website. So far the outputs look like this (for AAPL):
```
{'current': 216.24, 'low': 183.86, 'high': 300.0, 'mean': 235.47, 'median': 240.0}
```
```
numberOfAnalysts   avg   low  high  yearAgoEps  growth
0q                 25  1.59  1.53  1.63        1.36   0.169
+1q                20  2.40  2.21  2.61        2.04   0.176
0y                 36  6.70  6.64  6.75        5.73   0.169
+1y                37  7.49  6.88  8.00 …
```
> Implement Analysis (no scraping)

- yfinance/scrapers/history.py
Also handle volume=0 rows often being in different currency unit to other rows.
> Fix price-repair-currency, logic was inverted

- README.md
- tests/test_ticker.py
- yfinance/base.py
- yfinance/scrapers/funds.py
- yfinance/ticker.py
Changes:
- adding to scraper a new class `FundsData`.
- Ticker can now reference the data via `ticker.funds_data` when appropriate. When the ticker symbol is not that of a fund's, the code will throw an error when a parameter of `funds_data` is called. i.e. `yf.Ticker('AAPL').funds_data.description`
- Add unit tests in `test_ticker.py` for the funds data
- minor change to `test_ticker.py` as `YFChartError` was removed from code in https://github.com/ranaroussi/yfinance/pull/2000
Resolves:
- https://github.com/ranaroussi/yfinance/issues/244
- https://github.com/ranaroussi/yfinance/issues/422
- https://github.com/ranaroussi/yfinance/issues/684
- https://github.com/ranaroussi/yfinance/discussions/1761
- https://github.com/ranaroussi/yfinance/discussions/2012
Sample Code:
``` python
import …
```
> implement support for funds data

- yfinance/multi.py
Remade this to fix issue #899 
From previous PR,
> I don't see any good reason to treat single element symbol lists passed to yfinance.Tickers as something special, instead perform the pandas.concat like you would normally (with multiple tickers).
Avoids a KeyError raised here,
https://github.com/ranaroussi/yfinance/blob/9e2252e4516304efbd52d05ad66a5beb9a900e5e/yfinance/tickers.py#L83
> fix keyerror with single element list passed to Tickers

- .github/workflows/pyright.yml
- pyrightconfig.json
- requirements.txt
This PR introduces Pyright, a static type checker for Python, into the yfinance project. The purpose is to ensure type safety and improve code quality by identifying type-related issues during development.
- **Type Safety**: Pyright helps in detecting type errors early in the development process, reducing runtime errors and improving reliability.  
- **Improved Documentation**: With type annotations, the code becomes more self-explanatory and easier to understand, aiding in code maintenance and collaboration.
- Created a new GitHub Action `pyright.yml` that triggers on pull requests to the master and main branches for automatic type checking.
> Add Pyright type checking

- yfinance/screener/screener.py
Quick fix for issue https://github.com/ranaroussi/yfinance/issues/2093
This broke yfinance for me after I automatically upgraded to the latest release.
Existing tests should suffice. Directly targeting `main` because the release is broken
> Fix malformed f-string in release `0.2.45`

- tests/test_ticker.py
- yfinance/multi.py
Fix minor regression in 0.2.45 (#2068)
Should fix issue #2106
> Fix times appearing in output from yf.download(ignore_tz=True)

- yfinance/utils.py
When making a request to "{_BASE_URL_}/v1/finance/search?q={isin}", the response doesn't always has a 'longname' field and this throws an error.
Example with this isin : IE00BDBRDM35
> fixed a bug throwing an error when trying to get a ticker from certain isin

- tests/test_ticker.py
- yfinance/scrapers/analysis.py
Summary
- LTG (long-term growth ?) is new to the API but its meaning is not shown on yahoo yet.
- Support for 5 year numbers seem to have been removed. so commenting it out.
- Fixes: https://github.com/ranaroussi/yfinance/issues/2126
Examples: LTG row and 5 year numbers are not shown in the links below.
- https://finance.yahoo.com/quote/MSFT/analysis/
- https://finance.yahoo.com/quote/AAPL/analysis/
- https://finance.yahoo.com/quote/TSLA/analysis/
Sample:
import yfinance as yahooFinance
```Python
msft = yahooFinance.Ticker("MSFT")
print(msft.growth_estimates) # now works
```
> Fix growth_estimates for new key `LTG`

- yfinance/multi.py
Makes yf.download() to default to auto_adjust=True to align its behavior with Ticker.history()
> Default yf.download() to auto adjust prices

- yfinance/base.py
Resolves #2075 
- Updated `get_news()` in `Ticker` to get up to 200 news articles (previously 8-10)
- The method now fetches news directly from the ticker's news page (https://finance.yahoo.com/quote/MSFT/latest-news/) instead of using the previous search based approach which was limiting
```python
news = yf.Ticker("MSFT").news
print(len(news))
```
- **Breaking change**: The returned data structure/schema has changed. Further feedback is required on how to proceed.
> Feature: Fetch upto 200 news articles

- yfinance/base.py
Currently, get_earnings_dates doesn't work.
According to the below thread, it looks like YahooFinance changed their earnings format.
https://github.com/ranaroussi/yfinance/issues/1932#issuecomment-2518039027
I would like to add [Alex-Naxitus](https://github.com/Alex-Naxitus)'s code contribution to the original yfinance.
I've tested this code and get_earnings_dates works great.
> Fix get_earnings_dates method

- yfinance/data.py
- yfinance/exceptions.py
- yfinance/scrapers/history.py
- New `YfRateLimitError` exception class, which is raised regardless of `raise_errors`
- Raises the above exception if the response from Yahoo! Finance returns `429` status code.
Tricky. Can test it with any `yfinance` function. Would need to spam Yahoo! Finance until you get rate limited. But here is an example of how it looks:
> Raise Exception if Rate Limited

- README.md
- doc/source/reference/examples/market.py
- doc/source/reference/index.rst
- doc/source/reference/yfinance.market.rst
- yfinance/__init__.py
- yfinance/domain/market.py
> Add market Summary

- yfinance/search.py
The search class was not using all the capabilities given by yahoo. This adds them.
> Update Search class to allow more options

- tests/test_ticker.py
- yfinance/scrapers/analysis.py
Removed hard coded keys in the Analysis scraper functions to protect against Yahoo changing the keys in the future.
End result is more or else the same except:
- Few column names have changed
- Index has names
Closes #2188
> Fix: Remove hardcoded keys in Analysis

- doc/source/reference/examples/search.py
- tests/test_search.py
- yfinance/search.py
Retrieving quotes using `Search` was returning an extra row.
```python
{
'index': '78ddc07626ff4bbcae663e88514c23a0',
'name': 'AAPlasma',
'permalink': 'aaplasma',
'isYahooFinance': False
}
```
> Fix: Extra key in Search quotes

- tests/test_ticker.py
- tests/test_utils.py
- yfinance/exceptions.py
- yfinance/scrapers/history.py
- yfinance/utils.py
Fix regression introduced by #2192 that broke the functionality of the `dev` branch while implementing custom periods.
`Ticker.history()` and `download()` methods were broken.
> Fix: Restore dev branch regression with Ticker.history()

- yfinance/multi.py
Warn users that `download` changed `auto_adjust` to `True`.
Resolve #2225 #2219 #2214 #2198
> Warn user when use download() without specifying auto_adjust

- doc/source/conf.py
The "See also" links in the documentation (e.g., [yfinance.screener](https://ranaroussi.github.io/yfinance/reference/yfinance.screener.html)) are broken.
> Fix: Broken "See also" links in documentation

- yfinance/multi.py
- Fixed interval checking logic, intervals like `60m` and `90m` were previously not recognized.
- Updated error message formatting #2251 
```python
[*********************100%***********************]  27 of 27 completed
2 Failed downloads:
['AISUDFYHAOISDUFHA', 'ASDFSF']: YFTzMissingError('possibly delisted; no timezone found')
```
> Fix: Interval check and error message formatting in `multi.py`

- yfinance/scrapers/history.py
Extend div-repair to intraday
Increase lookback for "div date wrong"
Slightly loosen default "false threshold" for cluster of mixed False/True
Related:
Stop checking for down-changes after negative adj-close Handle avg-volume=0%
> Improve prices div repair

- doc/source/reference/yfinance.financials.rst
- tests/test_ticker.py
- yfinance/base.py
- yfinance/scrapers/fundamentals.py
- yfinance/ticker.py
This PR completes the earlier #1643 and moves the PR in to the dev branch.
- Fetches the TTM values for cash flow and income statement from Yahoo.
- Added tests test_ttm_income_statement and test_ttm_cash_flow.
- Transferring commit to dev branch
This feature was also requested in #2287
Obsoletes PR #2320
> Direct TTM Financial Data Retrieval Feature

- yfinance/scrapers/quote.py
- Check that result is not zero length before appending it to query_info
This resolves issue #2343
> Fixes issue 2343

- yfinance/base.py
Yahoo now returning earnings dates in UTC, stop assuming it's in exchange TZ
Fix #2365
I'll stress-test before merging
> Fix earnings dates tz

- tests/test_ticker.py
- yfinance/base.py
- yfinance/scrapers/history.py
- `history()` now only caches data if the period is `max`
- Renamed `_history` to `_max_history` to ensure clarity
- Added a test to ensure proper behavior for chained history calls
Closes #2344
> Fix: History caching

- tests/test_ticker.py
- yfinance/base.py
- yfinance/utils.py
- In utils.py line 196 if the session is None then _requests is mistakenly passed to as session to data.py which causes attribute error: module 'requests.cookies' has no attribute 'update'
- The above condition happens only when searching tickers with ISIN numbers
- Added tests with ISIN numbers
- Added tickerBase to raise an ValueError if an empty tickername is passed or isin search results in to empty ticker. This is to have consistent behaviour with utils.get_all_by_isin()
This PR requires that PR #2382 is first merged otherwise new tests introduced for ISIN will fail to same error as #2343 and #2363
> Fixes issues 2301 and 2383 AttributeError: module 'requests.cookies' has no attribute 'update'

- doc/source/reference/examples/lookup.py
- doc/source/reference/index.rst
- doc/source/reference/yfinance.search.rst
- tests/test_lookup.py
- yfinance/__init__.py
- yfinance/lookup.py
The `Search` module seems like it has been heavily nerfed for searching just tickers. It seems more useful now for fetching news.
I have therefore added a new class `Lookup` that provides the functionality as provided on this page
https://finance.yahoo.com/lookup/?s=apple
To perform the same as the link above:
```python
all = yf.Lookup("apple").all
print(all)
```
Closes #2359
> Feature: Ticker lookups

- tests/test_utils.py
- yfinance/scrapers/history.py
- yfinance/utils.py
Fixes #2206 
Also fix post-market interval being discarded.
Bonus: adding the dropped row to metadata as "lastTrade", looks like just time and single price is useful.
> Fix fix_Yahoo_returning_live_separate()

- meta.yaml
- requirements.txt
- setup.py
- yfinance/base.py
- yfinance/data.py
- yfinance/multi.py
- yfinance/scrapers/history.py
- yfinance/utils.py
~**Don't merge this!**~
~This is just a temporary workaround to allow yfinance to work if using an impersonated session from curl_cffi. Probably is better to actually incorporate curl_cffi into yfinance itself rather than require the session to be passed in to all requests, but this works for now.~
Made the change myself to use curl_cffi by default. Tested by downloading some data and appears to work locally.
> Incorporate curl_cffi to avoid rate limiting and cookie errors

- yfinance/scrapers/history.py
This PR is to address the primary problem in issue #2451 - around yf.download with period="max".
There was a bug that interval="2m" was not accounted for.
Intraday intervals often fail due to processing time - which leads to requesting a period of data that exceeds the maximum period. In reducing a buffer from the calculated end and start dates, the error is avoided.
Also, the 1m interval chunk was increased to 8 days as this is the actual max requestable period/chunk.
**--This time without automated formatting changes--** 
Cheers,
Cole
> adjusting for processing time in max period (reduced)

- yfinance/scrapers/fundamentals.py
Not sure how long the financials tables have been `object` dtype not `float`. Suddenly my codes began breaking but I don't see any recent relevant changes.
before:
```
>>> dat.income_stmt.dtypes
2024-12-31    object
2023-12-31    object
2022-12-31    object
2021-12-31    object
2020-12-31    object
dtype: object
```
after:
```
>>> dat.income_stmt.dtypes
2024-12-31    float64
2023-12-31    float64
2022-12-31    float64
2021-12-31    float64
2020-12-31    float64
```
> Financials: ensure dtype float

- tests/test_ticker.py
This PR fixes the bug in: https://github.com/ranaroussi/yfinance/issues/2576
The unit test now pass:
```
python3 -m unittest tests.test_ticker
```
```
Ran 64 tests in 25.539s
OK
```
> Fix test_ticker unit test failure due to NEPT delisting
